### ISSUE TITLE
[Linux] desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [FormidableLabs/electron-webpack-dashboard#13]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

For example:

```
[Desktop Entry]
Name=Webpack Dashboard
Comment=Webpack Dashboard
Exec=AppRun
Terminal=false
Type=Application
Icon=webpack-dashboard-app
X-AppImage-Version=0.1.0-beta.2
X-AppImage-BuildId=7039a870-8362-11a7-13de-27f5aa0eed21
```

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html), it should contain, for example:

```
Categories=Network;
```

Please test the result with `desktop-file-validate` and make sure it passes.

Reference: https://github.com/electron-userland/electron-builder/issues/1965

**Comment by probonopd** [comment]
electron-builder has a fix for this available:
https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1

**Comment by develar** [comment]
@probonopd I have already sent PR to this project ;) https://github.com/FormidableLabs/electron-webpack-dashboard/pull/12

**Comment by probonopd** [comment]
I hereby officially declare that _you rock_ ;-)

**Comment by kenwheeler** [comment]
Closing, will be in next release (today-ish)
