### ISSUE TITLE
Can't install with cask

### ISSUE THREAD

**Issue by godban** [FormidableLabs/electron-webpack-dashboard#14]
```shell
⇝ brew cask install webpack-dashboard
Error: Cask 'webpack-dashboard' is unavailable: No Cask with this name exists.
Error: Install incomplete.
```

**Comment by kenwheeler** [comment]
cc @pascaliske https://github.com/caskroom/homebrew-cask/pull/37744

**Comment by pascaliske** [comment]
@godban which version of homebrew do you use?
Can you try to update homebrew using `brew update && brew upgrade`?

**Comment by godban** [comment]
was 1.2.6, updated to 1.3.1. Loads fine now, thank you
