### ISSUE TITLE
Multiple simultaneous views?

### ISSUE THREAD

**Issue by wmertens** [FormidableLabs/electron-webpack-dashboard#15]
I have a hot-reloading server build and a hot-reloading client build. Would it be possible to keep the two dashboards separate somehow?

**Comment by kenwheeler** [comment]
In the next release I'll have port config, so you could do a different port for each

**Comment by wmertens** [comment]
Will it be possible to show each webpack in its own window, or should I be
running two instances of the app?

Actually, would it be hard to select a random token at plugin start and
differentiate webpack instances that way? And then when data comes in, open
a new window if the token differs…

**Comment by carlospaelinck** [comment]
Support for multiple instances of Electron Webpack Dashboard with different port configurations will be in the next release for macOS and Windows.
