### ISSUE TITLE
Can't completely uninstall 

### ISSUE THREAD

**Issue by danieleleoni** [FormidableLabs/electron-webpack-dashboard#19]
Hi guys,

yesterday I tried you package on a separated branch
Today I switched back on `master`, but yarn can't finish to install deps and stuck on
`warning "webpack-dashboard@1.0.0-4" has incorrect peer dependency "webpack@*".`
even if webpack-dashboard isn't nor in package.json or yarn.lock

I already delete and re-download my repo from scratch and remove with `brew cask uninstall webpack-dashboard`
Any idea?

Thanks

**Comment by kenwheeler** [comment]
is it in dev deps?

**Comment by kenwheeler** [comment]
1.0.0-4 is the plugin, not the app. did you install it globally?

**Comment by danieleleoni** [comment]
nope, locally with yarn

**Comment by kenwheeler** [comment]
have you removed node_modules?

**Comment by kenwheeler** [comment]
where do you see that error?
