### ISSUE TITLE
While developing with plugin, memory is rapidly consumed

### ISSUE THREAD

**Issue by dannyrb** [FormidableLabs/electron-webpack-dashboard#20]
> Please provide a description of the bug / issue, and provide the details below:

====================================================================

When including the `webpack-dashboard` plugin, as I save/develop/rebuild, my computer quickly runs out of memory. If I open Task Manager, I can see many instances of the Node.js running in task manager consuming a large portion of memory.

If I remove `webpack-dashboard` from my plugins, my memory sits at 50%. I've removed/added the plugin multiple times to verify that the issue persists and is caused by the plugin.

###### If the issue is visual, please provide screenshots here

====================================================================

Not a visual issue.

###### Steps to reproduce the problem

====================================================================

- Setup and use `vue-webpack-boilerplate`
- Follow the install/setup instructions in this repos readme for adding `webpack-dashboard` (via NPM)
- `npm run dev`
- Develop, making changes as you go

###### Please provide a gist of relevant files

My starting point: https://github.com/vuejs-templates/webpack
I add `new DashboardPlugin()` to the list of plugins for the `webpack.dev.conf.js`

1. package.json (specifically the script you are using to start the dashboard)
2. webpack.config.js
3. index.js (Your express based dev server, if applicable)

====================================================================

###### More Details

- What operating system are you on? **Windows 10 Pro**
- What terminal application are you using? **Powershell**
- What version of webpack-dashboard are you using? **1.0.0-2**
- What is the output of running `echo $TERM`? **No Output**

**Comment by kenwheeler** [comment]
Are you using the latest versions?

**Comment by kenwheeler** [comment]
Can you try using 1.0.0-4? Also, can I see a screenshot of your task manager?

**Comment by dannyrb** [comment]
[Task Manager Screen Shot](https://www.screencast.com/t/BF47yXeeN)

Each save seems to spawn another process. Memory consumption increases. You can see 10+ Node.js processes running. I'll update to latest and edit in my results.

**Comment by kenwheeler** [comment]
Interesting, @tptee do you think this is the daemon getting run each time?

**Comment by kenwheeler** [comment]
@dannyrb just cut a release, can you try npm install webpack-dashboard@v1.0.0-5 and see if its still happening for you?

**Comment by tibuurcio** [comment]
While using it today at work I noticed the same thing happening. Multiple Node processes being spawned and my computer froze at some point. I'm not sure if I was on `1.0.0-4`. Will check it tomorrow.

I was on Ubuntu, please let me know if there's any test I can do to help!

**Comment by kenwheeler** [comment]
1.0.0-5 of the plugin should do it. The daemon was getting initialized on run, and I changed it to only initialize in the constructor.

**Comment by dannyrb** [comment]
`@next` wasn't pulling `1.0.0-5` for me, but `install @1.0.0-5` did the trick.

I'm no longer experiencing this issue (thanks for the quick fix, and the awesome plugin).
Feel free to close this issue if you're happy with the fix :+1:
