### ISSUE TITLE
How do you start it?

### ISSUE THREAD

**Issue by idkjs** [FormidableLabs/electron-webpack-dashboard#26]
I have a create-react-app ejected project. Installed via brew cask.
Installed with `yarn add webpack-dashboard@next --save-dev`

Added following to webpack.config.dev.js
```
const DashboardPlugin = require('webpack-dashboard/plugin');

plugins: [
  // ... your other plugins
    new DashboardPlugin()
  ],
```

Then ran yarn start. Nothing happening. 

Thank you.

**Comment by xjamundx** [comment]
Are you also running the electron dashboard app?

**Comment by idkjs** [comment]
i only installed the electron dashboard app as noted above. How do I start the electron-dashboard app? Is there something else I need to install?

Thank you!

**Comment by kenwheeler** [comment]
Yup, download the actual app binary, available here in Win/OSX/Linux flavors. Run that, then yarn start, an you should be able to see telemetry start flowing in: https://github.com/FormidableLabs/electron-webpack-dashboard/releases/tag/v0.1.0-beta.5

**Comment by idkjs** [comment]
Followed steps, got a prompt that it was already in Applications folder so I guess I missed that prompt or there wasn't one. Thanks for the help.
