### ISSUE TITLE
[bug]`yarn build` could not complete

### ISSUE THREAD

**Issue by YutHelloWorld** [FormidableLabs/electron-webpack-dashboard#28]
## version

webpack-dashboard@next

## configure

same as readMe.md

## description

When I run `yarn build`, it would not complete with logging  'Done xxx s'  .Travis CI like this
![image](https://user-images.githubusercontent.com/20860159/29750631-bba62fd4-8b75-11e7-9e9b-be3e92d53cfd.png)
![image](https://user-images.githubusercontent.com/20860159/29750633-cc02c180-8b75-11e7-981f-7a0bac976b2c.png)

Travis CI: https://travis-ci.org/YutHelloWorld/vortex-react/builds/268907303?utm_source=github_status&utm_medium=notification
PR: https://github.com/YutHelloWorld/vortex-react/pull/27

@kenwheeler

**Comment by kenwheeler** [comment]
Closing, saw you sorted it with the dev flag
