### ISSUE TITLE
"Source is not a function error" when trying to compile.

### ISSUE THREAD

**Issue by stephan-v** [FormidableLabs/electron-webpack-dashboard#29]
I am currently getting this error:

```
/app/node_modules/webpack-dashboard/plugin/index.js:50
source: stats.compilation.assets[bundlePath].source()

TypeError: stats.compilation.assets[bundlePath].source is not a function    
```

If I quickly dive into the node modules folder and replace the function call with a property call everything works fine.

**Comment by kenwheeler** [comment]
Closing, with a move to the webpack-dashboard base repo
