### ISSUE TITLE
Feature request: Adjustable font-size

### ISSUE THREAD

**Issue by sybrendotinga** [FormidableLabs/electron-webpack-dashboard#30]
I find the font-size of the output to large. When it is smaller, more of the output can be read. That would make it even easier to debug. Maybe, in the future, it can be a setting?

![schermafbeelding 2017-08-31 om 11 20 26](https://user-images.githubusercontent.com/14016492/29916278-93636c6e-8e3e-11e7-8b69-eeb94f8dfd03.png)

**Comment by rawrmonstar** [comment]
Addressed by #36 which adds keyboard shortcuts to increase, decrease, and reset font sizes.  When we add a settings modal I expect we'll add font size as a setting there as well.
