### ISSUE TITLE
Layout bug on smaller window sizes

### ISSUE THREAD

**Issue by nathobson** [FormidableLabs/electron-webpack-dashboard#4]
No errors = layout is fine. On this error, the layout screws up the log panel. Looks like the long path name is causing the issue. There is a line break but only after the hyphen.

Medium size window, right panel becomes crazy thin:
![screen shot 2017-08-17 at 14 09 11](https://user-images.githubusercontent.com/6664210/29414082-8620fbc2-8356-11e7-853a-5bd98da1660b.png)

Small screen size (all stacked panels) and the log window stretches off the screen:
![screen shot 2017-08-17 at 14 10 05](https://user-images.githubusercontent.com/6664210/29414083-86220ca6-8356-11e7-89c2-342eef0baa5b.png)

Thanks for the release!

**Comment by kenwheeler** [comment]
Have this fixed locally, getting pushed up in the next release
