### ISSUE TITLE
How to set up with create-react app?

### ISSUE THREAD

**Issue by tomitrescak** [FormidableLabs/electron-webpack-dashboard#59]
Hi, it seems that the project does not work with create-react-app (rewired).

Webpack: 3.10.0
Binary application running.
Plugin added and when logged reports this:

```
DashboardPlugin {
    host: '127.0.0.1',
    port: 9838,
    root: undefined,
    gzip: true,
    minified: true,
    handler: null,
    cleanup: [Function: bound cleanup],
    watching: false } ]
```

This is how I added the plugin using the rewired functionality:

```
// config-overrides.js
function rewireLoaderPlugin(config, env, definePluginOptions = {}) {
  // Add the define plugin to the list of plugins
  config.plugins = (config.plugins || [])
    .concat([new DashboardPlugin()])
  return config
}

module.exports = {
  webpack: function(config, env) {
    const rewires = compose(
      ...
      rewireLoaderPlugin
    );

    return rewires(config, env);
  }
};
```

Any idea what may be happening? Am still not getting any telemetry.

**Comment by ryan-roemer** [comment]
Rewiring may muck with how webpack-dashboard inserts itself. If you have a moment, could you open a minimal repository with:

* A CRA app that uses `webpack-dashboard` directly (not `electron-webpack-dashboard`). (Or report back to us here if only `e-w-d` hits the error).
* Install + error reproduction steps.

And then we'll clone the repo, install, and diagnose from there. Thanks!!!

**Comment by tomitrescak** [comment]
@ryan-roemer thanks for a fast response. The test repo is here: https://github.com/tomitrescak/webpack-dashboard-rewired

All you need to do is do the typical `yarn` and `yarn start`.

The truth is that not even the webpack-dashboard kicks in, although I can clearly see the webpack-dashboard in the list of added plugins.

**Comment by tomitrescak** [comment]
Unfortunately I cannot explain how, but when I created a new project from scratch all works as expected.
