### ISSUE TITLE
"Problems" not showing any data

### ISSUE THREAD

**Issue by saadq** [FormidableLabs/electron-webpack-dashboard#7]
Hey, awesome project. I had a question about the "Problems" panel in the bottom right. I thought that the linting error (the one you can see in the top left console) would show up in the bottom right as a "Problem". Shouldn't it be there or am I misunderstanding what that "Problems" box is for?

![screen shot 2017-08-17 at 9 44 30 am](https://user-images.githubusercontent.com/5678694/29415395-ef2a7254-8330-11e7-9850-8abf511a6b06.png)

**Comment by saadq** [comment]
No, there wasn't any `min+gz` thing there like you have in your screenshot. And cool, I'll be on the lookout for that.

**Comment by kenwheeler** [comment]
Just pushed up the next version. If there are errors you'll see them. If you do see them, hover over them and paste here and I'll reopen
