### ISSUE TITLE
[macOS] Invisible scroll bars

### ISSUE THREAD

**Issue by christianhg** [FormidableLabs/electron-webpack-dashboard#9]
Thanks a lot for this tool!

I don't know much about Electron apps or how they adhere to OS settings, but even though "Show scroll bars" is set to "Always" I don't get any visible scroll bars in the panels on macOS.

![screen shot 2017-08-17 at 21 30 44](https://user-images.githubusercontent.com/4602382/29430112-70f99906-8393-11e7-90c2-28687e5757fc.png)

![screen shot 2017-08-17 at 21 26 18](https://user-images.githubusercontent.com/4602382/29429963-dd68d1a2-8392-11e7-8d59-e8b0c2e245ad.png)

**Comment by kenwheeler** [comment]
So if you have light scroll bars, or are on windows, it looks REALLY bad. So I hid them because I couldn't find an OS targeted way to do it. Open to suggestion here.

**Comment by kenwheeler** [comment]
Closing, will reopen pending feedback
